version: '2'

services:
  # Guacamole daemon that connects to the desktops
  guacd:
    image: glyptodon/guacd:0.9.9
    container_name: intermediate.guacd
    networks:
      - default

  # Backend database used by Guacamole
  mysql:
    image: guacdb
    container_name: intermediate.guacdb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole
    networks:
      - default

  # This is the actual Guacamole web server
  guac:
    image: glyptodon/guacamole:0.9.9
    container_name: intermediate.guac
    depends_on:
      - guacd
      - mysql
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - default

  # Nginx proxy
  proxy:
    build: images/proxy
    container_name: intermediate.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - guac
    environment:
      VIRTUAL_HOST: demo.ewi.tudelft.nl
    ports:
      - 80:80
    networks:
      - default

  # Blender desktop image
  blender:
    image: blender
    container_name: intermediate.blender
    environment:
      BLENDER_FILE: shopping_cart.blend
    networks:
      - default
