version: '2'

services:
  guacd:
    image: glyptodon/guacd:0.9.9
    container_name: intermediate.guacd
    networks:
      - default

  mysql:
    image: guacdb
    container_name: intermediate.guacdb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole
    networks:
      - default

  guac:
    image: glyptodon/guacamole:0.9.9
    container_name: intermediate.guac
    depends_on:
      - guacd
      - mysql
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - default

  proxy:
    build: images/proxy
    container_name: intermediate.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - guac
    environment:
      VIRTUAL_HOST: demo.ewi.tudelft.nl
    ports:
      - 80:80
    networks:
      - default

  blender:
    image: bbmri.registry.ewi.tudelft.nl/sandbox/blender
    container_name: intermediate.blender