version: '2'

services:
  gw_guacd:
    image: glyptodon/guacd:0.9.9
    container_name: gw.advanced.guacd

  gw_guacdb:
    image: gw_guacdb
    container_name: gw.advanced.mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole

  gw_guac:
    image: glyptodon/guacamole:0.9.9
    container_name: gw.advanced.guac
    depends_on:
      - gw_guacd
      - gw_guacdb
    environment:
      MYSQL_HOSTNAME: gw_guacdb
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: gw_guacd
      GUACD_PORT_4822_TCP_PORT: 4822

  gw_proxy:
    build: images/gw_proxy
    container_name: gw.advanced.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - gw_guac
      - gw_flask
    networks:
      - default
    ports:
      - 8081:80

  gw_flask:
    build: images/gw_flask
    container_name: gw.advanced.flask
    depends_on:
      - gw_guac
    volumes:
      - ./images/gw_flask:/flask:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default