version: '2'

services:
  guacd:
    image: glyptodon/guacd:0.9.9
    container_name: demo.ewi.tudelft.nl.guacd

  mysql:
    image: bbmri.registry.ewi.tudelft.nl/sandbox/guacdb
    container_name: demo.ewi.tudelft.nl.mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole

  guac:
    image: glyptodon/guacamole:0.9.9
    container_name: demo.ewi.tudelft.nl.guac
    depends_on:
      - guacd
      - mysql
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822

  proxy:
    build: images/proxy
    container_name: demo.ewi.tudelft.nl.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - guac
    environment:
      VIRTUAL_HOST: demo.ewi.tudelft.nl
    networks:
      - gateway
      - default