version: '2'

services:
  gw_guacd:
    image: glyptodon/guacd:0.9.9
    container_name: gw.intermediate.guacd
    networks:
      - default

  gw_guacdb:
    image: gw_guacdb
    container_name: gw.intermediate.guacdb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole
    networks:
      - default

  gw_guac:
    image: glyptodon/guacamole:0.9.9
    container_name: gw.intermediate.guac
    depends_on:
      - gw_guacd
      - gw_guacdb
    environment:
      MYSQL_HOSTNAME: gw_guacdb
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: gw_guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - default

  gw_proxy:
    build: images/gw_proxy
    container_name: gw.intermediate.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - gw_guac
    ports:
      - 80:80
    networks:
      - default

  gw_blender:
    image: gw_blender
    container_name: gw.intermediate.blender
    environment:
      BLENDER_FILE: shopping_cart.blend
    networks:
      - default
