version: '2'

services:
  # Guacamole daemon that connects to the desktops
  gw_guacd:
    image: glyptodon/guacd:0.9.9
    container_name: gw.intermediate.guacd
    networks:
      - default

  # Backend database used by Guacamole
  gw_guacdb:
    # Guacamole database image from the local Docker registry (created in the prerequisites section)
    image: guacdb
    container_name: gw.intermediate.guacdb
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: guacamole
    networks:
      - default

  # This is the actual Guacamole web server
  gw_guac:
    image: glyptodon/guacamole:0.9.9
    container_name: gw.intermediate.guac
    depends_on:
      - gw_guacd
      - gw_guacdb
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: root
      MYSQL_PASSWORD: demo
      GUACD_PORT_4822_TCP_ADDR: guacd
      GUACD_PORT_4822_TCP_PORT: 4822
    networks:
      - default

  # Nginx proxy
  gw_proxy:
    build: images/proxy
    container_name: gw.intermediate.proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - gw_guac
    ports:
      - 80:80
    networks:
      - default

  # Blender container
  blender:
    # Blender image from the local Docker registry (created in the prerequisites section)
    image: blender
    container_name: gw.intermediate.blender
    environment:
      # The mesh model to load in Blender
      BLENDER_FILE: shopping_cart.blend
    networks:
      - default
